#!/bin/bash
clear
red='\033[31;1m'
green='\033[32;1m'
clear
echo $green"___  ____ ____ _  _    ____ ____ _    _"
echo "|  \ |  | |__/ |_/  __ [__  |  | |    |"
echo "|__/ |__| |  \ | \_    ___] |_\| |___ |"
echo ""
sleep 2
echo $red"|--------------------------------|"
echo $red"|inurl:index.php?id=             |"
echo "|================================|"
echo "|inurl:trainers.php?id=          |"
echo "|================================|"
echo "|inurl:buy.php?category=         |"
echo "|================================|"
echo "|inurl:article.php?ID=           |"
echo "|================================|"
echo "|inurl:play_old.php?id=          |"
echo "|================================|"
echo "|inurl:Pageid=                   |"
echo "|================================|"
echo "|inurl:games.php?id=             |"
echo "|================================|"
echo "|inurl:page.php?file=            |"
echo "|================================|"
echo "|inurl:newsDetail.php?id=        |"
echo "|================================|"
echo "|inurl:gallery.php?id=           |"
echo "|================================|"
echo "|inurl:show.php?id=              |"
echo "|================================|"
echo "|inurl:staff_id=                 |"
echo "|================================|"
echo "|            Done✓               |"
echo "|        Created By : R24        |"
echo "|    Thanks For Using This Tool  |"
echo "|--------------------------------|"
