#!/bin/bash
red='\033[31;1m'
green='\033[32;1m'
clear
echo $green"_ _ _ ____ ___     _  _ _  _ _    _  _"
echo "| | | |___ |__] __ |  | |  | |    |\ |"
echo "|_|_| |___ |__]     \/  |__| |___ | \|"
echo ""
sleep 2
echo $red"|----------------------------|"
echo "|http://www.asnurotomotiv.com |"
echo "|=============================|"
echo "|http://www.besirozer.com     |"
echo "|=============================|"
echo "|http://www.bms-co.com.tr     |"
echo "|=============================|"
echo "|http://www.dakkik.com        |"
echo "|=============================|"
echo "|http://www.fulyagm.com       |"
echo "|=============================|"
echo "|http://www.galeriapollo.com  |"
echo "|=============================|"
echo "|http://www.kusadasirealestate.com"
echo "|=============================|"
echo "|http://www.malianaliz.net    |"
echo "|=============================|"
echo "|http://www.maliyorum.com     |"
echo "|=============================|"
echo "|http://www.merdiven.com      |"
echo "|=============================|"
echo "|http://www.merdivenhalisi.com|"
echo "|============================="
echo "|http://www.nennycollection.com"
echo "|=============================|"
echo "|http://www.ozerahsap.com     |"
echo "|=============================|"
echo "|http://www.ozermerdivenmarket.com"
echo "|=============================|"
echo "|http://www.ozerstair.com     |"
echo "|=============================|"
echo "|http://www.ozerstairs.com    |"
echo "|=============================|"
echo "|http://www.portatifmerdiven.com"
echo "|=============================|"
echo "|http://www.savocats.com      |"
echo "|=============================|"
echo "|http://www.sinor.com.tr      |"
echo "|=============================|"
echo "|http://www.teraelektronik.com|"
echo "|=============================|"
echo "|http://duschk.icc.sa         |"
echo "|=============================|"
echo "|http://e-ctasia.com          |"
echo "|=============================|"
echo "|http://news.e-ctasia.com     |"
echo "|=============================|"
echo "|http://shop.e-ctasia.com     |"
echo "|=============================|"
echo "|http://blog.e-ctasia.com     |"
echo "|=============================|"
echo "|http://info.e-ctasia.com     |"
echo "|=============================|"
echo "|http://admin.e-ctasia.com    |"
echo "|=============================|"
echo "|http://contact.e-ctasia.com  |"
echo "|=============================|"
echo "|http://mail.e-ctasia.com     |"
echo "|=============================|"
echo "|http://forum.e-ctasia.com    |"
echo "|=============================|"
echo "|http://product.e-ctasia.com  |"
echo "|=============================|"
echo "|            Done✓             |"
echo "|        Created By : R24        |"
echo "|    Thanks For Using This Tool|"
echo "|-----------------------------|"
